blog/urls.py
from django.urls import path
from .views import (PostListView,
                    PostCreateView,
                    PostDetailView,
                    PostUpdateView,
                    PostDeleteView,
                    UserPostListView,
                    about)

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    # pk is the default argument for primary keys so we don't have to tell the class about which instance to display
    path('post/<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('post/new/', PostCreateView.as_view(), name='create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='delete'),
    path('user/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('about/', about, name='about'),
]

blog_site/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset-done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    # to have access to the media files on the specified location on the settings file while debugging
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    # this method is used to redirect the user to the created Post after creating or updating  it
    # django by default searches for this method after creating a post
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{ self.user.username } Profile'

    def save(self, force_insert=False, force_update=False, using=None):
        super().save()
        img = Image.open(self.image.path)
        if img.height > 300 or img.width < 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

blog/views.py
from django.shortcuts import render
from .models import Post
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DeleteView, UpdateView, DetailView, CreateView
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'  # the default is blog/post_list.html
    context_object_name = 'posts'
    ordering = ['-date_posted']  # from latest to oldest
    # we can also specify the query set we want to display as a list
    # queryset = Post.objects.filter(title='First Post')  posts with title 'First Post'
    #  .. the default gives us all the posts
    paginate_by = 5  # two posts per page


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'  # the default is blog/post_list.html
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5  # page_obj variable is sent to the template automatically as the current page instance

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(DetailView):  # the default template is blog/post_detail.html
    model = Post
    # the default object context passed is 'object' to be used on the template
    # the id is passed in the url as <int:pk> which is the default for django


# the LoginRequiredMixin doing the functionality of the loginrequired decorator for methods
# and it is used with class based views and it is passed before the other classes
class PostCreateView(LoginRequiredMixin, CreateView):  # the template for this view is modelName_form ( post_form.html )
    model = Post
    fields = ['title', 'content']

    # this method is used to assign fields automatically
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    # this method is used to assign fields automatically
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    # this function is required by the UserPassesTestMixin and should return true if the
    # user trying to edit the post is the same user that wrote it
    def test_func(self):
        return self.request.user == self.get_object().author


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/' # send them to the home page

    def test_func(self):
        return self.request.user == self.get_object().author


def about(request):
    return render(request, 'blog/about.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm, ProfileUpdateForm, UserUpdateForm
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Your account has successfully been created .. now you can log in')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', context={'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        u_form = UserUpdateForm(request.POST, instance=request.user)
        if p_form.is_valid() and u_form.is_valid():
            p_form.save()
            u_form.save()
            messages.success(request, f'Your Profile has been updated')
            return redirect('profile')
        else:
            p_form = ProfileUpdateForm(instance=request.user.profile)
            u_form = UserUpdateForm(instance=request.user)
            print("form data are not valid")
    else:
        p_form = ProfileUpdateForm(instance=request.user.profile)
        u_form = UserUpdateForm(instance=request.user)
    return render(request, 'users/profile.html', {'p_form': p_form, 'u_form': u_form})

blog/templates/blog/about.html
{% extends 'blog\base.html' %}

{% block content %}
    <h1>About page</h1>
{% endblock content %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog\main.css' %}">
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Django blog</title>
    {% endif %}
</head>
<body>

    <!-- the navigation bar -->
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'blog:home' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'blog:home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'blog:about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'blog:create' %}">New Post</a>
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                    <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                {% else %}
                  <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                  <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <!-- the body (will be overridden) -->
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/home.html
{% extends 'blog\base.html' %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'blog:user-posts' post.author.username %}">{{ post.author.username }}</a>
                <!-- display the date in the form (Month Day, Year) like ( March 04, 2019 )  -->
              <small class="text-muted">{{ post.date_posted|date:'F d, Y' }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}

    <!-- pagination part  -->
    {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ page_obj.number }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-5' and num < page_obj.number|add:'5' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}
{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog\base.html' %}
{% block content %}
    <div class="content-section">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post {{ object.title }}</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'blog:detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'blog\base.html' %}
{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{% url 'blog:user-posts' object.author.username %}">{{ object.author.username }}</a>
            <!-- display the date in the form (Month Day, Year) like ( March 04, 2019 )  -->
          <small class="text-muted">{{ object.date_posted|date:'F d, Y' }}</small>
            {% if object.author == user %}
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blog:update' object.id %}">Update</a>
                    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:delete' object.id %}">Delete</a>
                </div>
            {% endif %}
        </div>
        <h2 class="article_title">{{ object.title }}</h2>
        <p class="article-content">{{ object.content }}</p>
      </div>
    </article>
{% endblock content %}

blog/templates/blog/post_form.html
{% extends 'blog\base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/user_posts.html
{% extends 'blog\base.html' %}
{% block content %}
    <h1 class="mb-4">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for post in posts %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'blog:user-posts' post.author.username %}">{{ post.author.username }}</a>
                <!-- display the date in the form (Month Day, Year) like ( March 04, 2019 )  -->
              <small class="text-muted">{{ post.date_posted|date:'F d, Y' }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}

    <!-- pagination part  -->
    {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ page_obj.number }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-5' and num < page_obj.number|add:'5' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}
{% endblock content %}

users/templates/users/login.html
{% extends 'blog\base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log in now</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-info" type="submit">Log in</button>
                <small class="text-muted ml-2">
                    <a href="{% url 'password_reset' %}">Forgot Password?</a>
                </small>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an account? <a class="ml-2" href="{% url 'register' %}">Sign Up</a>
            </small>
        </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends 'blog\base.html' %}
{% block content %}
    <h3>You are logged out</h3>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Login Again</a>
        </small>
    </div>
{% endblock content %}

users/templates/users/password_reset.html
{% extends 'blog\base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-info" type="submit">Request Password Reset</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends 'blog\base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="alert alert-info">
        Your password has been successfully reset
        <a href="{% url 'login' %}">Sign In here</a>
    </div>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends 'blog\base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends 'blog\base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="alert alert-info">
        An email has been sent to reset your password
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends 'blog\base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <form enctype='multipart/form-data' method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile Info</legend>
            {{ u_form|crispy }}
            {{ p_form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-info" type="submit">Update</button>
        </div>
    </form>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends 'blog\base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already have an account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}